# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a243a8b18c555ffcd51ba468f8ffd5a7e3b71992fc5ccc1333ffa2e2070b0cce3801323c60514e4e7f9bfbd2c2f83ecfcc351fe8387f5f2a8050097a1cb383c2

test:
  secret_key_base: 00aca4f4b370cc02aefd6d1988c2c7349921ba918df4be4d62f7747204a5da00d68e2c3054813840c4f4dc18ab9dd129650ec57eccf0ea4741661cbf8f0d59ea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
